[package]
name = "fair_main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.6"
clap = "4"
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
config = "0.13"
tokio = { version = "1", features = ["full"] }